"""Regenerate Trace Signal's deterministic fictional examples."""

from __future__ import annotations

from pathlib import Path
import sys

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from tracesignal.examples import make_demo_events, make_starter_template  # noqa: E402


def main() -> None:
    examples = ROOT / "examples"
    examples.mkdir(exist_ok=True)
    demo = make_demo_events()
    template = make_starter_template()
    demo.to_csv(examples / "tracesignal-fictional-event-log.csv", index=False)
    template.to_csv(examples / "tracesignal-starter-template.csv", index=False)
    with pd.ExcelWriter(examples / "tracesignal-fictional-event-log.xlsx", engine="openpyxl") as writer:
        demo.to_excel(writer, sheet_name="events", index=False)
        pd.DataFrame(
            [
                {"field": "status", "value": "Entirely fictional data generated by code."},
                {"field": "unit", "value": "One row per touchpoint event inside a journey."},
            ]
        ).to_excel(writer, sheet_name="read_me", index=False)
    with pd.ExcelWriter(examples / "tracesignal-starter-template.xlsx", engine="openpyxl") as writer:
        template.to_excel(writer, sheet_name="events", index=False)


if __name__ == "__main__":
    main()
